name: 'Check Commit Messages'

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        env:
          GH_PKG_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v5
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
